### ISSUE TITLE
Error when run the tool

### ISSUE THREAD

**Issue by MindPatch** [random-robbie/bugbountydork#1]
````
┌─[✗]─[root@kali]─[~/bugbountydork]
└──╼ #python main.py -d testphp.vulnweb.com
````
Name of error :
urllib2.HTTPError: HTTP Error 429: Too Many Requests
OS : Kali Linux

**Comment by ladecruze** [comment]
Hi @knassar702 After certain number of requests, you will see this error message, try connecting to vpn, it will help you! 

- Thanks,
   Ladecruze

**Comment by MindPatch** [comment]
ok .. Thanks @ladecruze  :)
